# Generated by Django 5.2.4 on 2026-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.CharField(max_length=30, unique=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('ctc', models.CharField(blank=True, max_length=100)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], default='Draft', max_length=20)),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='offer_letters/%Y/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'offers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_id', models.CharField(max_length=30, unique=True)),
                ('employee_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('joining_date', models.DateField(blank=True, null=True)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('Documents Pending', 'Documents Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], default='Documents Pending', max_length=30)),
                ('task_profile', models.BooleanField(default=False, verbose_name='Profile Completed')),
                ('task_offer', models.BooleanField(default=False, verbose_name='Offer Accepted')),
                ('task_docs_upload', models.BooleanField(default=False, verbose_name='Documents Uploaded')),
                ('task_docs_verify', models.BooleanField(default=False, verbose_name='Documents Verified')),
                ('task_bgc', models.BooleanField(default=False, verbose_name='Background Check')),
                ('task_checkin', models.BooleanField(default=False, verbose_name='Day-1 Check-in')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'onboarding_records',
                'ordering': ['joining_date'],
            },
        ),
    ]
