# Generated by Django 5.2.4 on 2026-07-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrecord',
            name='aadhar_card',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/aadhar/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='aadhar_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='bank_holder_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='bank_ifsc',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='bank_passbook',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/bank/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='class10_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/marks10/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='class12_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/marks12/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='degree_certificate',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/degree/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='driving_license',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/license/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='esi_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='experience_certificate',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/experience/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='pan_card',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/pan/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='pan_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='passport_photo',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/photos/%Y/'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='pf_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='professional_certificate',
            field=models.FileField(blank=True, null=True, upload_to='onboarding/prof/%Y/'),
        ),
    ]
