# Generated by Django 5.2.4 on 2026-07-09 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_onboardingrecord_aadhar_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrecord',
            name='rejected_docs',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AddField(
            model_name='onboardingrecord',
            name='verified_docs',
            field=models.TextField(blank=True, default='[]'),
        ),
    ]
