# Generated by Django 5.2.4 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_onboardingrecord_rejected_docs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='joining_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Sent', 'Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Expired', 'Expired')], db_index=True, default='Draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='onboardingrecord',
            name='joining_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='onboardingrecord',
            name='status',
            field=models.CharField(choices=[('Documents Pending', 'Documents Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed')], db_index=True, default='Documents Pending', max_length=30),
        ),
    ]
