# Generated by Django 5.2.4 on 2026-07-21 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobrequest_existing_role'),
        ('onboarding', '0005_alter_offer_joining_date_alter_offer_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='jobs.existingrole'),
        ),
    ]
