# Generated by Django 5.2.4 on 2026-07-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobposting_existing_role'),
        ('onboarding', '0006_offer_existing_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboardingrecord',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onboarding_records', to='jobs.existingrole'),
        ),
    ]
