# Generated by Django 5.2.4 on 2026-07-22 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_generalapplication_existing_role'),
        ('onboarding', '0007_onboardingrecord_existing_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='general_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='applications.generalapplication'),
        ),
        migrations.AddField(
            model_name='offer',
            name='job_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers', to='applications.jobapplication'),
        ),
    ]
