# Generated by Django 5.2.4 on 2026-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=30, unique=True)),
                ('preferred_role', models.CharField(blank=True, max_length=200)),
                ('preferred_dept', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], default='Applied', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'general_applications',
                'ordering': ['-applied_date'],
            },
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=30, unique=True)),
                ('role', models.CharField(max_length=200)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('cover_letter', models.TextField(blank=True)),
                ('notice_period', models.CharField(blank=True, max_length=50)),
                ('has_referral', models.BooleanField(default=False)),
                ('referral_emp_id', models.CharField(blank=True, max_length=50)),
                ('referred_by', models.CharField(blank=True, max_length=200)),
                ('applied_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Offer Sent', 'Offer Sent'), ('Offer Accepted', 'Offer Accepted'), ('Withdrawn', 'Withdrawn')], default='Applied', max_length=20)),
                ('admin_note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'job_applications',
                'ordering': ['-applied_date'],
            },
        ),
    ]
