# Generated by Django 5.2.4 on 2026-07-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generalapplication',
            name='preferred_dept',
        ),
    ]
