# Generated by Django 5.2.4 on 2026-07-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_generalapplication_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Rejected', 'Rejected')], db_index=True, default='Applied', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Shortlisted', 'Shortlisted'), ('Selected', 'Selected'), ('Rejected', 'Rejected'), ('Offer Sent', 'Offer Sent'), ('Offer Accepted', 'Offer Accepted'), ('Withdrawn', 'Withdrawn')], db_index=True, default='Applied', max_length=20),
        ),
    ]
