# Generated by Django 5.2.4 on 2026-07-22 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_generalapplication_status_and_more'),
        ('jobs', '0017_jobposting_existing_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalapplication',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_applications', to='jobs.existingrole'),
        ),
    ]
