# Generated by Django 5.2.4 on 2026-07-22 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_generalapplication_existing_role'),
        ('jobs', '0018_approvalhistory_acted_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_applications', to='jobs.existingrole'),
        ),
    ]
