# Generated by Django 5.2.4 on 2026-07-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolerequest",
            name="experience",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="rolerequest",
            name="salary_range",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
