# Generated by Django 5.2.4 on 2026-07-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_add_salary_experience_to_role_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Sent Back', 'Sent Back')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Sent Back', 'Sent Back')], default='Pending', max_length=20),
        ),
    ]
