# Generated by Django 5.2.4 on 2026-07-01 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_jobrequest_status_alter_rolerequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='existingrole',
            name='department',
            field=models.CharField(max_length=100),
        ),
    ]
