# Generated by Django 5.2.4 on 2026-07-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_alter_existingrole_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
