# Generated by Django 5.2.4 on 2026-07-01 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobrequest_description_jobrequest_justification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='educational_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
    ]
