# Generated by Django 5.2.4 on 2026-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_jobrequest_educational_qualifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='educational_qualifications',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='skills_required',
            field=models.TextField(blank=True),
        ),
    ]
