# Generated by Django 5.2.4 on 2026-07-03 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_add_cancelled_status_to_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requests', to='jobs.jobcategory'),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
