# Generated by Django 5.2.4 on 2026-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobrequest_category_jobrequest_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrequest',
            name='qualification',
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='educational_qualifications',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
