# Generated by Django 5.2.4 on 2026-07-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_remove_jobrequest_qualification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='channel',
            field=models.CharField(choices=[('External', 'External'), ('Internal', 'Internal'), ('Career Page', 'Career Page')], default='External', max_length=20),
        ),
    ]
