# Generated by Django 5.2.4 on 2026-07-08 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_alter_jobposting_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='type',
            field=models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50),
        ),
    ]
