# Generated by Django 5.2.4 on 2026-07-18 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_rolerequest_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='experience',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rolerequest',
            name='type',
            field=models.CharField(blank=True, choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50, null=True),
        ),
        migrations.CreateModel(
            name='RoleRequestVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Full-time', 'Full-time'), ('Part-time', 'Part-time'), ('Contract', 'Contract'), ('Internship', 'Internship')], default='Full-time', max_length=50)),
                ('experience', models.CharField(blank=True, max_length=50)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('role_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variations', to='jobs.rolerequest')),
            ],
            options={
                'db_table': 'role_request_variations',
            },
        ),
    ]
