# Generated by Django 5.2.4 on 2026-07-21 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_rolerequest_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_requests', to='jobs.existingrole'),
        ),
    ]
