# Generated by Django 5.2.4 on 2026-07-21 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_rolerequest_existing_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_requests', to='jobs.existingrole'),
        ),
    ]
