# Generated by Django 5.2.4 on 2026-07-22 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_jobrequest_existing_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='postings', to='jobs.existingrole'),
        ),
    ]
