# Generated by Django 5.2.4 on 2026-07-22 18:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobposting_existing_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalhistory',
            name='acted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_history_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalrequest',
            name='submitted_by_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_requests_submitted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='existingrole',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='existing_roles', to='jobs.jobcategory'),
        ),
    ]
