# Generated by Django 5.2.4 on 2026-06-25 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0002_email_as_login'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
