# Generated by Django 5.2.4 on 2026-07-07 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_resumefile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidateprofile',
            name='preferred_dept',
        ),
        migrations.RemoveField(
            model_name='candidateprofile',
            name='preferred_role',
        ),
    ]
