# Generated by Django 5.2.4 on 2026-07-22 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobposting_existing_role'),
        ('users', '0003_remove_candidateprofile_preferred_dept_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='interested_roles',
            field=models.ManyToManyField(blank=True, related_name='interested_candidates', to='jobs.existingrole'),
        ),
    ]
