# Generated by Django 5.2.4 on 2026-07-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_candidateprofile_interested_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_picture',
            field=models.TextField(blank=True),
        ),
    ]
