# Generated by Django 5.2.4 on 2026-07-22 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_candidateprofile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumefile',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resume_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
