# Generated by Django 5.2.4 on 2026-07-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_approvalhistory_acted_by_user_and_more'),
        ('users', '0006_resumefile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='occupants', to='jobs.existingrole'),
        ),
    ]
