# Generated by Django 5.2.4 on 2026-06-26 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panelist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'panelists',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_id', models.CharField(max_length=30, unique=True)),
                ('candidate_name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('score', models.PositiveIntegerField(blank=True, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Next Round', 'Next Round')], max_length=20)),
                ('feedback', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], default='Scheduled', max_length=20)),
                ('mode', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline')], default='Online', max_length=20)),
                ('meeting_link', models.URLField(blank=True)),
                ('round', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='applications.jobapplication')),
                ('panel', models.ManyToManyField(blank=True, related_name='interviews', to='interviews.panelist')),
            ],
            options={
                'db_table': 'interviews',
                'ordering': ['-date', '-time'],
            },
        ),
    ]
