# Generated by Django 5.2.4 on 2026-07-06 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_interview_reminder_sent_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='recommendation',
            field=models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Next Round', 'Next Round'), ('Strong Hire', 'Strong Hire'), ('Hire', 'Hire'), ('Hold', 'Hold'), ('Reject', 'Reject'), ('Pending', 'Pending')], max_length=20),
        ),
    ]
