# Generated by Django 5.2.4 on 2026-07-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0003_alter_interview_recommendation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
