# Generated by Django 5.2.4 on 2026-07-14 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_alter_interview_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criteria', models.JSONField(blank=True, default=dict)),
                ('custom_criteria', models.JSONField(blank=True, default=dict)),
                ('overall_score', models.PositiveIntegerField(blank=True, editable=False, null=True)),
                ('recommendation', models.CharField(blank=True, choices=[('Selected', 'Selected'), ('Rejected', 'Rejected'), ('On Hold', 'On Hold'), ('Next Round', 'Next Round'), ('Strong Hire', 'Strong Hire'), ('Hire', 'Hire'), ('Hold', 'Hold'), ('Reject', 'Reject'), ('Pending', 'Pending')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.interview')),
                ('panelist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='interviews.panelist')),
            ],
            options={
                'db_table': 'interview_evaluations',
                'constraints': [models.UniqueConstraint(fields=('interview', 'panelist'), name='unique_interview_panelist_evaluation')],
            },
        ),
    ]
