# Generated by Django 5.2.4 on 2026-07-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_interviewevaluation'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_present',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
