# Generated by Django 5.2.4 on 2026-07-21 19:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0008_alter_interview_date_alter_interview_status'),
        ('jobs', '0016_jobrequest_existing_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='existing_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='jobs.existingrole'),
        ),
    ]
