# Generated by Django 5.2.4 on 2026-07-22 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_generalapplication_existing_role'),
        ('interviews', '0009_interview_existing_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='general_application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interviews', to='applications.generalapplication'),
        ),
        migrations.AddField(
            model_name='panelist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='panelist_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
