# Generated by Django 5.2.4 on 2026-07-22 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0010_interview_general_application_panelist_user'),
        ('jobs', '0018_approvalhistory_acted_by_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='panelist',
            name='specialties',
            field=models.ManyToManyField(blank=True, related_name='qualified_panelists', to='jobs.existingrole'),
        ),
    ]
